from bots.commands.base_command import BaseCommand
import psycopg2
import os
import time

class PlaybackCommand(BaseCommand):

    @staticmethod
    def name():
        return "playback"

    # For now, just check that a single arg exists
    def _validate(self):
        validity = True
        if len(self.args) < 2:
            validity =  False
        return validity

    # Play latest sound generated by the user
    def _execute(self):
        with psycopg2.connect(os.environ["DB_URL"].strip()) as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT pcm_chunk
                    FROM (
                        SELECT pcm_chunk, ROW_NUMBER() OVER (PARTITION BY username ORDER BY created_at DESC) as rnum
                        FROM sound_chunks
                        WHERE lower(username) = lower(%(username)s)
                        LIMIT %(offset)s
                    ) pcm
                    WHERE rnum = %(offset)s;
                """, {"username": self.args[0], "offset": self.args[1]})
                sound_chunks = cur.fetchall()
                print(cur.query)
        conn.close()

        for pcm in sound_chunks:
            sound = bytes(pcm[0])
            time.sleep(0.5)
            self.mumble.sound_output.add_sound(sound)