from bots.commands.base_command import BaseCommand
import psycopg2
import os
import time

class PlaybackAliasCommand(BaseCommand):

    @staticmethod
    def name():
        return "playback-alias"

    # For now, just check that a single arg exists
    def _validate(self):
        validity = True
        if len(self.args) < 1:
            validity =  False
        return validity

    # Play latest sound generated by the user
    def _execute(self):
        with psycopg2.connect(os.environ["DB_URL"].strip()) as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT sound_chunk
                    FROM sound_aliases
                    WHERE name = %(name)s
                """, {"name": self.args[0]})
                sound_chunks = cur.fetchall()
                print(cur.query)
        conn.close()

        for pcm in sound_chunks:
            sound = bytes(pcm[0])
            self.mumble.sound_output.add_sound(sound)