from bots.commands.base_command import BaseCommand
import psycopg2
import os
import time

class PlaybackCommand(BaseCommand):

    @staticmethod
    def name():
        return "playback"

    # For now, just check that a single arg exists
    def _validate(self):
        validity = True
        if len(self.args) < 1:
            validity =  False
        return validity

    # Play latest sound generated by the user
    def _execute(self):
        with psycopg2.connect(os.environ["DB_URL"].strip()) as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT pcm_chunk 
                    FROM sound_chunks
                    WHERE username = '{}'
                    ORDER BY created_at DESC
                    LIMIT 1
                """.format(self.args[0]))
                sound_chunks = cur.fetchall()
        conn.close()
        
        for pcm in sound_chunks:
            sound = bytes(pcm[0])
            time.sleep(5)
            self.mumble.sound_output.add_sound(sound)