from bots.commands.base_command import BaseCommand
import psycopg2
import os
import time

class PlaybackConvo(BaseCommand):

    @staticmethod
    def name():
        return "playback-convo"

    # For now, just check that a single arg exists
    def _validate(self):
        validity = True
        return validity

    # Play latest sound generated by the user
    def _execute(self):
        with psycopg2.connect(os.environ["DB_URL"].strip()) as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT pcm_chunk
                    FROM (
                        SELECT pcm_chunk, created_at
                        FROM sound_chunks
                        ORDER BY created_at DESC
                        LIMIT 10
                    ) foo
                    ORDER BY created_at ASC
                """)
                sound_chunks = cur.fetchall()
                print(cur.query)
        conn.close()

        for pcm in sound_chunks:
            sound = bytes(pcm[0])
            self.mumble.sound_output.add_sound(sound)