from .base_command import BaseCommand
import psycopg2
import os
import time

class AliasCommand(BaseCommand):

    @staticmethod
    def name():
        return "alias"

    # For now, just check that a single arg exists
    def _validate(self):
        validity = True
        if len(self.args) < 3:
            validity =  False
        return validity

    # Play latest sound generated by the user
    def _execute(self):
        with psycopg2.connect(os.environ["DB_URL"].strip()) as conn:
            with conn.cursor() as cur:
                cur.execute("""
                INSERT INTO sound_aliases (name, sound_chunk)
                    SELECT %(name)s, pcm_chunk
                    FROM (
                        SELECT pcm_chunk, ROW_NUMBER() OVER (PARTITION BY username ORDER BY created_at DESC) as rnum
                        FROM sound_chunks
                        WHERE lower(username) = lower(%(username)s)
                        LIMIT %(offset)s
                    ) pcm
                    WHERE rnum = %(offset)s;
                """, {"username": self.args[0], "offset": self.args[1], "name": self.args[2]})
                conn.commit()
                print(cur.query)
        conn.close()